# Generated by Django 3.2.9 on 2022-03-17 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
