# Generated by Django 3.2.9 on 2022-03-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220317_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='book',
            new_name='book_id',
        ),
    ]
